language: node_js
node_js:
- '8'
- '10'
- '12'
dist: trusty
sudo: required
addons:
  chrome: stable
  apt:
    packages:
      - p7zip-full
env:
  global:
    - BASE_NAME=embetty-$TRAVIS_TAG
cache:
  yarn: true
  directories:
    - node_modules
script:
- yarn test
- yarn build
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
before_deploy: yarn build:zip
after_script: greenkeeper-lockfile-upload
deploy:
  - provider: npm
    skip_cleanup: true
    provider: npm
    email: npmjs@heise.de
    api_key:
      secure: "wRb3/QFjGIkh5l0wk6KNIXFihkRy0A798o3+UcN50XZmAZLN96WGKPBsYIYuKnD8erod4Iclcrs5IkdNdUkEZVbSeiTu9eZawghCmgqyW0jZUqe7d0GqJGFizu58ZDgp08DNJ3+lRkehVsluwWVqEIF9wPLiQS0Pbe8uqFONSzVxmFW8pKsTXLCwbNVZuPl+4BQZSx1nnQuanSpz2Of+pPT1NyOl8jKpcB9kUnmWe8WnASNbW7K6zBDrLkrNTmp2DE1ZTzXG4psj+AoSCo7SRUtJhhffXA0N2xO/jWfNHHyZVMDCT+YD8DQxnh8SAU75s+LA3l8ZT/0S6oBxBKUFf97qHEuV7Fhzjgkwk/rtKP9wgz7K+oQgVbgRjsIBo/+AysJs0XN0WIjUM5o9w3qfSu5wgKfXxf/nqZ8nc3sjfuA4FKK6CWGyGjXlV9mLSOj/u2Mqq4fsRfEFN8dw+NZUwcC9teNCSCepMCGsWuvEBcGB6+viArOoWcKLcn102+Da5TluOWKT1nBqD37fNCMF6r2zxX7bCQAYaVy2TKDcDjPp0+G/+Ui5KzUi5K34FNZaGlinKpHQIElRkmjDqN/HTBplDrP3ittPR8CNK3Humo3I3+LsI/x9VrrfhrSL21qB5lEON38hdtaXZ5Tud4j50LWD+qySejv56BtKBZN/OPU="
    on:
      tags: true
      repo: heiseonline/embetty
      node_js: '8'
  - provider: releases
    api_key:
      secure: "pQTUUSHprolW8fE7MerxZBRoxk2HleoYyfwgFZI9ZQ50Tx6jtUKRgwTJc5jckJpgNLu9FVM0D0Z8v037CRk4Wd4UWSSc0OCmR0FKqlhGD1sppRVPRhvayfviCMsTRlUgD3ge2kjpuN+XfGzntem6Jfq69tf3q7/xfMW7RXEga8+KE2l+jB3Bhc8y18rI547jwiDN4n/Dwf2AlndZp+a0ssVklC7sY6IomyoSstpJG6tKDNBgIfIDM0lszd/mjhEzlDaEKqJVF9v00OSFt5p+jqnJAfZfCDiX1w0NFgjwbRMyCYJLmmYLi1ge/KEDQ1b1TAVO4tuMvQAZ/FextJvimqx9cIPzfLXHdjTMh3tBFAK1fNPeoK8+ZMce3TE3H17YDUbUKnQZXW+Dr02bFlXvP3zW0CAOYjhCDsoiVjuUyQF2NcNgvSgDGplp8xu2WrEzRh7DRxuBhfQwe6Y1YIo+TvDy9qj0gxbUf98W+f680drpIf6v/Io7XVTIj2BZZYM9ulZywberCP0XWN4pal/nLQCloEXUZjTBOIBuBdimOBl5IwYBKZX+Km0oMtKtKEcIydn+KxRlyVpbqCI4MNMdnR0hJ0UfYgOeF+K+QGJZwxtgxMw7UQGgxaASYWY37jS+LkECI1+ZYS0cNx6del9eC/24E/EJu9u/neCSSv4YMwI="
    file:
      - $BASE_NAME.zip
      - $BASE_NAME.tar.gz
    skip_cleanup: true
    on:
      tags: true
      repo: heiseonline/embetty
      node_js: '8'
